SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* FactoryFlow - Dichiarazione Fine Processo.
   Additive, idempotent, no DROP, no FK to AdHoc. */

IF COL_LENGTH('dbo.FF_DICHIARAZIONI_PRODUZIONE', 'IdProcesso') IS NULL
    ALTER TABLE dbo.FF_DICHIARAZIONI_PRODUZIONE ADD IdProcesso int NULL;
GO
IF COL_LENGTH('dbo.FF_DICHIARAZIONI_PRODUZIONE', 'IdVersioneProcesso') IS NULL
    ALTER TABLE dbo.FF_DICHIARAZIONI_PRODUZIONE ADD IdVersioneProcesso int NULL;
GO
IF COL_LENGTH('dbo.FF_DICHIARAZIONI_PRODUZIONE', 'IdAttivita') IS NULL
    ALTER TABLE dbo.FF_DICHIARAZIONI_PRODUZIONE ADD IdAttivita bigint NULL;
GO
IF COL_LENGTH('dbo.FF_DICHIARAZIONI_PRODUZIONE', 'TipoDichiarazione') IS NULL
    ALTER TABLE dbo.FF_DICHIARAZIONI_PRODUZIONE ADD TipoDichiarazione varchar(30) NULL;
GO

IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_FF_DICHIARAZIONI_PRODUZIONE_PROCESSI' AND parent_object_id = OBJECT_ID('dbo.FF_DICHIARAZIONI_PRODUZIONE'))
    ALTER TABLE dbo.FF_DICHIARAZIONI_PRODUZIONE ADD CONSTRAINT FK_FF_DICHIARAZIONI_PRODUZIONE_PROCESSI FOREIGN KEY (IdProcesso) REFERENCES dbo.FF_PROCESSI_PRODUTTIVI(IdProcesso);
GO
IF NOT EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_FF_DICHIARAZIONI_PRODUZIONE_VERSIONI' AND parent_object_id = OBJECT_ID('dbo.FF_DICHIARAZIONI_PRODUZIONE'))
    ALTER TABLE dbo.FF_DICHIARAZIONI_PRODUZIONE ADD CONSTRAINT FK_FF_DICHIARAZIONI_PRODUZIONE_VERSIONI FOREIGN KEY (IdVersioneProcesso) REFERENCES dbo.FF_PROCESSI_VERSIONI(IdVersione);
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name = 'IX_FF_DICHIARAZIONI_PRODUZIONE_Processo' AND object_id = OBJECT_ID('dbo.FF_DICHIARAZIONI_PRODUZIONE'))
    CREATE INDEX IX_FF_DICHIARAZIONI_PRODUZIONE_Processo ON dbo.FF_DICHIARAZIONI_PRODUZIONE(IdProcesso, IdVersioneProcesso, DataProduzione);
GO

IF OBJECT_ID(N'dbo.FF_DICHIARAZIONI_FINE_PROCESSO', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.FF_DICHIARAZIONI_FINE_PROCESSO
    (
        IdFineProcesso bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_FF_DICHIARAZIONI_FINE_PROCESSO PRIMARY KEY,
        IdDichiarazione bigint NOT NULL,
        IdProcesso int NULL,
        IdVersione int NULL,
        IdAttivita bigint NULL,
        CodArticolo varchar(30) NOT NULL,
        QuantitaProdotta decimal(18,6) NOT NULL,
        DataProduzione date NOT NULL,
        OraInizio datetime2(0) NULL,
        OraFine datetime2(0) NULL,
        Stato varchar(20) NOT NULL CONSTRAINT DF_FF_DICHIARAZIONI_FINE_PROCESSO_Stato DEFAULT ('CONFERMATA'),
        TempoTotaleMinuti decimal(18,3) NULL,
        SetupTotaleMinuti decimal(18,3) NULL,
        ProduttivitaReale decimal(18,6) NULL,
        Note varchar(1000) NULL,
        DataCreazione datetime2(0) NOT NULL CONSTRAINT DF_FF_DICHIARAZIONI_FINE_PROCESSO_DataCreazione DEFAULT (SYSDATETIME()),
        UtenteCreazione varchar(50) NULL,
        CONSTRAINT FK_FF_DICHIARAZIONI_FINE_PROCESSO_DICHIARAZIONI FOREIGN KEY (IdDichiarazione) REFERENCES dbo.FF_DICHIARAZIONI_PRODUZIONE(IdDichiarazione),
        CONSTRAINT FK_FF_DICHIARAZIONI_FINE_PROCESSO_PROCESSI FOREIGN KEY (IdProcesso) REFERENCES dbo.FF_PROCESSI_PRODUTTIVI(IdProcesso),
        CONSTRAINT FK_FF_DICHIARAZIONI_FINE_PROCESSO_VERSIONI FOREIGN KEY (IdVersione) REFERENCES dbo.FF_PROCESSI_VERSIONI(IdVersione),
        CONSTRAINT FK_FF_DICHIARAZIONI_FINE_PROCESSO_ATTIVITA FOREIGN KEY (IdAttivita) REFERENCES dbo.FF_ATTIVITA_PRODUTTIVE(IdAttivita),
        CONSTRAINT CK_FF_DICHIARAZIONI_FINE_PROCESSO_Ore CHECK (OraInizio IS NULL OR OraFine IS NULL OR OraFine > OraInizio)
    );
    CREATE UNIQUE INDEX UX_FF_DICHIARAZIONI_FINE_PROCESSO_Dichiarazione ON dbo.FF_DICHIARAZIONI_FINE_PROCESSO(IdDichiarazione);
    CREATE INDEX IX_FF_DICHIARAZIONI_FINE_PROCESSO_Processo ON dbo.FF_DICHIARAZIONI_FINE_PROCESSO(IdProcesso, IdVersione, DataProduzione);
END;
GO

IF OBJECT_ID(N'dbo.FF_DICHIARAZIONI_FASI', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.FF_DICHIARAZIONI_FASI
    (
        IdDichiarazioneFase bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_FF_DICHIARAZIONI_FASI PRIMARY KEY,
        IdFineProcesso bigint NOT NULL,
        IdFase int NULL,
        Sequenza int NOT NULL,
        CodFase varchar(40) NOT NULL,
        Descrizione varchar(200) NOT NULL,
        IdLineaPrevista int NULL,
        IdLineaEffettiva int NULL,
        IdMacchinaPrevista int NULL,
        IdMacchinaEffettiva int NULL,
        IdTeamPrevisto int NULL,
        IdTeamEffettivo int NULL,
        OraInizioEffettiva datetime2(0) NULL,
        OraFineEffettiva datetime2(0) NULL,
        TempoEffettivoMinuti decimal(18,3) NULL,
        SetupEffettivoMinuti decimal(18,3) NULL,
        NoteAnomalie varchar(1000) NULL,
        DataCreazione datetime2(0) NOT NULL CONSTRAINT DF_FF_DICHIARAZIONI_FASI_DataCreazione DEFAULT (SYSDATETIME()),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_FINE_PROCESSO FOREIGN KEY (IdFineProcesso) REFERENCES dbo.FF_DICHIARAZIONI_FINE_PROCESSO(IdFineProcesso),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_FASI FOREIGN KEY (IdFase) REFERENCES dbo.FF_PROCESSI_FASI(IdFase),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_LINEA_PREV FOREIGN KEY (IdLineaPrevista) REFERENCES dbo.FF_LINEE_LAVORAZIONE(IdLinea),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_LINEA_EFF FOREIGN KEY (IdLineaEffettiva) REFERENCES dbo.FF_LINEE_LAVORAZIONE(IdLinea),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_MAC_PREV FOREIGN KEY (IdMacchinaPrevista) REFERENCES dbo.FF_MACCHINE(IdMacchina),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_MAC_EFF FOREIGN KEY (IdMacchinaEffettiva) REFERENCES dbo.FF_MACCHINE(IdMacchina),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_TEAM_PREV FOREIGN KEY (IdTeamPrevisto) REFERENCES dbo.FF_TEAM_OPERATIVI(IdTeam),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_TEAM_EFF FOREIGN KEY (IdTeamEffettivo) REFERENCES dbo.FF_TEAM_OPERATIVI(IdTeam),
        CONSTRAINT CK_FF_DICHIARAZIONI_FASI_Ore CHECK (OraInizioEffettiva IS NULL OR OraFineEffettiva IS NULL OR OraFineEffettiva > OraInizioEffettiva)
    );
    CREATE INDEX IX_FF_DICHIARAZIONI_FASI_FINE_PROCESSO ON dbo.FF_DICHIARAZIONI_FASI(IdFineProcesso, Sequenza);
END;
GO

IF OBJECT_ID(N'dbo.FF_DICHIARAZIONI_FASI_RISORSE', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.FF_DICHIARAZIONI_FASI_RISORSE
    (
        IdDichiarazioneFaseRisorsa bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_FF_DICHIARAZIONI_FASI_RISORSE PRIMARY KEY,
        IdDichiarazioneFase bigint NOT NULL,
        IdMacchina int NULL,
        IdLinea int NULL,
        RuoloRisorsa varchar(50) NULL,
        OraInizio datetime2(0) NULL,
        OraFine datetime2(0) NULL,
        Note varchar(500) NULL,
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_RISORSE_FASE FOREIGN KEY (IdDichiarazioneFase) REFERENCES dbo.FF_DICHIARAZIONI_FASI(IdDichiarazioneFase),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_RISORSE_MAC FOREIGN KEY (IdMacchina) REFERENCES dbo.FF_MACCHINE(IdMacchina),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_RISORSE_LINEA FOREIGN KEY (IdLinea) REFERENCES dbo.FF_LINEE_LAVORAZIONE(IdLinea)
    );
    CREATE INDEX IX_FF_DICHIARAZIONI_FASI_RISORSE_Fase ON dbo.FF_DICHIARAZIONI_FASI_RISORSE(IdDichiarazioneFase);
END;
GO

IF OBJECT_ID(N'dbo.FF_DICHIARAZIONI_FASI_TEAM', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.FF_DICHIARAZIONI_FASI_TEAM
    (
        IdDichiarazioneFaseTeam bigint IDENTITY(1,1) NOT NULL CONSTRAINT PK_FF_DICHIARAZIONI_FASI_TEAM PRIMARY KEY,
        IdDichiarazioneFase bigint NOT NULL,
        IdTeam int NULL,
        IdOperatore int NULL,
        IdRuoloOperativo int NULL,
        NomeOperatoreSnapshot varchar(200) NULL,
        RuoloSnapshot varchar(100) NULL,
        CostoOrarioApplicato decimal(18,4) NULL,
        OraInizio datetime2(0) NULL,
        OraFine datetime2(0) NULL,
        Note varchar(500) NULL,
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_TEAM_FASE FOREIGN KEY (IdDichiarazioneFase) REFERENCES dbo.FF_DICHIARAZIONI_FASI(IdDichiarazioneFase),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_TEAM_TEAM FOREIGN KEY (IdTeam) REFERENCES dbo.FF_TEAM_OPERATIVI(IdTeam),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_TEAM_OPERATORI FOREIGN KEY (IdOperatore) REFERENCES dbo.FF_OPERATORI(IdOperatore),
        CONSTRAINT FK_FF_DICHIARAZIONI_FASI_TEAM_RUOLI FOREIGN KEY (IdRuoloOperativo) REFERENCES dbo.FF_RUOLI_OPERATIVI(IdRuoloOperativo)
    );
    CREATE INDEX IX_FF_DICHIARAZIONI_FASI_TEAM_Fase ON dbo.FF_DICHIARAZIONI_FASI_TEAM(IdDichiarazioneFase);
END;
GO
