SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;
GO

/* FactoryFlow - Macchina/Risorsa impiegata nella dichiarazione */

IF COL_LENGTH('dbo.FF_DICHIARAZIONI_PRODUZIONE', 'IdMacchina') IS NULL
BEGIN
    ALTER TABLE dbo.FF_DICHIARAZIONI_PRODUZIONE
        ADD IdMacchina int NULL;
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE name = 'FK_FF_DICHIARAZIONI_PRODUZIONE_MACCHINE'
      AND parent_object_id = OBJECT_ID('dbo.FF_DICHIARAZIONI_PRODUZIONE')
)
BEGIN
    ALTER TABLE dbo.FF_DICHIARAZIONI_PRODUZIONE
        ADD CONSTRAINT FK_FF_DICHIARAZIONI_PRODUZIONE_MACCHINE
        FOREIGN KEY (IdMacchina) REFERENCES dbo.FF_MACCHINE(IdMacchina);
END;

IF NOT EXISTS (
    SELECT 1
    FROM sys.indexes
    WHERE name = 'IX_FF_DICHIARAZIONI_PRODUZIONE_Macchina'
      AND object_id = OBJECT_ID('dbo.FF_DICHIARAZIONI_PRODUZIONE')
)
BEGIN
    CREATE INDEX IX_FF_DICHIARAZIONI_PRODUZIONE_Macchina
        ON dbo.FF_DICHIARAZIONI_PRODUZIONE(IdMacchina, DataProduzione);
END;

